const columns = [
    {
      field: "segmentCode",
      headerText: "Code",
      width: "20%",
      textAlign: "Right",
      id: 1,
    },
    {
      field: "sg",
      headerText: "SG",
      width: "20%",
      textAlign: "Right",
      id: 2,
    },
    {
      field: "lg",
      headerText: "LG",
      width: "20%",
      textAlign: "Right",
      id: 3,
    },
    {
      field: "segmentName",
      headerText: "Segment Name",
      width: "20%",
      textAlign: "Right",
      id: 4,
    },
    {
      field: "count",
      headerText: "Count",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 5,
      hasAccessor: true,
      precision: 2,
    },
    {
      field: "percentComp",
      headerText: "Percent Comp",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 6,
      hasAccessor: true,
      precision: 2,
    },
    {
      field: "baseCount",
      headerText: "Base Count",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 7,
      hasAccessor: true,
      precision: 2,
    },
    {
      field: "basePercent",
      headerText: "Base Percent",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 8,
      hasAccessor: true,
      precision: 2,
    },
    {
      field: "percentPen",
      headerText: "Percent Pen",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 9,
      hasAccessor: true,
      precision: 2,
    },
    {
      field: "index",
      headerText: "Index",
      width: "20%",
      textAlign: "Right",
      isNumeric: true,
      isHidable: true,
      id: 10,
      hasAccessor: true,
      precision: 0,
    },
  ];

  module.exports = { columns };
